FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt requirements.txt

RUN python -m pip install --upgrade pip \
    && pip install -r requirements.txt \
    && pip install torch==2.5.1 --index-url https://download.pytorch.org/whl/cpu

COPY . .

CMD ["python", "-m", "src.main"]
